config/routes.rb
Rails.application.routes.draw do

  root 'cocktails#index'

  resources :cocktails, only: [:show, :index, :new, :create, :destroy] do
    resources :doses, only: [:create]
  end

  resources :doses, only: [:destroy]

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true

  mount_uploader :picture, PictureUploader
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, :ingredient, presence: true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

  validates :name, presence: true, uniqueness: :true
  has_many :doses, dependent: :destroy
  has_many :cocktails, through: :doses

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :find_cocktail, only: [:show, :destroy]


  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])

  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :picture)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  before_action :set_cocktail, only: [ :create ]

  def create
    @dose = @cocktail.doses.build(dose_params)
    if @dose.save
      redirect_to @cocktail
    else
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to @dose.cocktail
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/delete.html.erb
<h1>Cocktails#delete</h1>
<p>Find me in app/views/cocktails/delete.html.erb</p>

app/views/cocktails/index.html.erb
<h1>Cocktails</h1>

<% @cocktails.each do |cocktail| %>
  <h2>
    <%= link_to cocktail do %>
      <%= cocktail.id %>. <%= cocktail.name %>
    <% end %>
  </h2>
  <%= cl_image_tag(cocktail.picture, width: 300, height: 200, crop: :fill) %>
<% end %>

app/views/cocktails/new.html.erb
<h1>Create a cocktail</h1>


<%= simple_form_for [@cocktail] do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :picture %>
  <%= f.button :submit %>
<% end %>

app/views/cocktails/show.html.erb
<div class="text-center">

  <h1><%= @cocktail.name %></h1>
  <%= cl_image_tag(@cocktail.picture, width: 300, height: 200, crop: :fill) %>

  <ul class="list-unstyled">
  <% @cocktail.doses.each do |dose| %>
    <li>
      <%= dose.description %> (<%= dose.ingredient.name %>) <%= link_to "&times;".html_safe , dose, method: :delete %>
    </li>
  <% end %>

  </ul>

  <br><br>

  <%= link_to "back to home", cocktails_path %>  |
  <%= link_to "destroy the cocktail", cocktail_path(@cocktail), method: :delete %>

  <hr>

  <%= link_to "add a new dose", @new_cocktail_dose_path %>

  <%= simple_form_for [@cocktail, @dose] do |f| %>

    <% if @dose.errors.any? %>
      <% @dose.errors.full_messages.each do |message| %>
        <li> <% message %> </li>
      <% end %>
    <% end %>

    <%= f.input :description, placeholder: "6cl au moins" %>
    <%= f.input :ingredient_id, collection: Ingredient.all, prompt: "Choose and ingredient !" %>
    <%= f.button :submit, class: "btn btn-primary" %>

  <% end %>

</div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/delete.html.erb
<h1>Doses#delete</h1>
<p>Find me in app/views/doses/delete.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#delete</h1>
<p>Find me in app/views/doses/delete.html.erb</p>

app/views/doses/index.html.erb
<h1>Doses#index</h1>

app/views/doses/new.html.erb
<h1>Add a new dose</h1>

<%= form_for [@dose] do |f| %>
  <%= f.label :description %><br>
  <%= f.text_field :description %><br>
  <%= f.submit "add a dose" %>
<% end %>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

app/views/ingredients/show.html.erb
<h2>Voici les cocktails qui contiennent "<%= @ingredient.name %>" </h2>


<ul>
  <% @ingredient.cocktails.each do |cocktail| %>
  <li>
    <%= cocktail.name %>
  </li>
  <% end %>
</ul>

app/views/layouts/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">

    <a href="">
      <%= image_tag "logo.jpg", class: "navbar-wagon-logo" %>
    </a>

    <div class="navbar-wagon-pusher"></div>

    <hr>
    <%= link_to t(".top_call_to_action", default: "Créer un nouveau cocktail"), new_cocktail_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- app/views/layouts/application.html.erb -->
<head>
  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>
  <title>Mister Cocktail</title>
    <!--  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %> -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/navbar" %>

<div class="container">

<%= yield %>

</div>

</body>
</html>